name: Learn Julia

on:
  push:
    branches: [main]

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:

      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup-py-env
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install-pkg
        run: pip install -r "chore/requirements.txt"

      - name: generate-readme
        run: python "chore/toc.py"

      - name: commit-change
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "ci: auto generate" && git push || echo "No changes to commit"